/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript.impl;

import duc.uscript.uScript.ByteTypeRef;
import duc.uscript.uScript.UScriptPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Byte Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ByteTypeRefImpl extends SingleTypeRefImpl implements ByteTypeRef
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ByteTypeRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UScriptPackage.Literals.BYTE_TYPE_REF;
  }

} //ByteTypeRefImpl
