/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript.impl;

import duc.uscript.uScript.ClassRef;
import duc.uscript.uScript.UScriptPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Class Ref</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.impl.ClassRefImpl#getReferencedClass <em>Referenced Class</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClassRefImpl extends SingleTypeRefImpl implements ClassRef
{
  /**
   * The cached value of the '{@link #getReferencedClass() <em>Referenced Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getReferencedClass()
   * @generated
   * @ordered
   */
  protected duc.uscript.uScript.Class referencedClass;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClassRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UScriptPackage.Literals.CLASS_REF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public duc.uscript.uScript.Class getReferencedClass()
  {
    if (referencedClass != null && referencedClass.eIsProxy())
    {
      InternalEObject oldReferencedClass = (InternalEObject)referencedClass;
      referencedClass = (duc.uscript.uScript.Class)eResolveProxy(oldReferencedClass);
      if (referencedClass != oldReferencedClass)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, UScriptPackage.CLASS_REF__REFERENCED_CLASS, oldReferencedClass, referencedClass));
      }
    }
    return referencedClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public duc.uscript.uScript.Class basicGetReferencedClass()
  {
    return referencedClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setReferencedClass(duc.uscript.uScript.Class newReferencedClass)
  {
    duc.uscript.uScript.Class oldReferencedClass = referencedClass;
    referencedClass = newReferencedClass;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, UScriptPackage.CLASS_REF__REFERENCED_CLASS, oldReferencedClass, referencedClass));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case UScriptPackage.CLASS_REF__REFERENCED_CLASS:
        if (resolve) return getReferencedClass();
        return basicGetReferencedClass();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case UScriptPackage.CLASS_REF__REFERENCED_CLASS:
        setReferencedClass((duc.uscript.uScript.Class)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case UScriptPackage.CLASS_REF__REFERENCED_CLASS:
        setReferencedClass((duc.uscript.uScript.Class)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case UScriptPackage.CLASS_REF__REFERENCED_CLASS:
        return referencedClass != null;
    }
    return super.eIsSet(featureID);
  }

} //ClassRefImpl
