/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript.impl;

import duc.uscript.uScript.GaussianRef;
import duc.uscript.uScript.UScriptPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Gaussian Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class GaussianRefImpl extends UTypeRefImpl implements GaussianRef
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GaussianRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UScriptPackage.Literals.GAUSSIAN_REF;
  }

} //GaussianRefImpl
