/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript.impl;

import duc.uscript.uScript.ShortTypeRef;
import duc.uscript.uScript.UScriptPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Short Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ShortTypeRefImpl extends SingleTypeRefImpl implements ShortTypeRef
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ShortTypeRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UScriptPackage.Literals.SHORT_TYPE_REF;
  }

} //ShortTypeRefImpl
