/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript.impl;

import duc.uscript.uScript.UScriptPackage;
import duc.uscript.uScript.VoidTypeRef;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Void Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class VoidTypeRefImpl extends SingleTypeRefImpl implements VoidTypeRef
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VoidTypeRefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return UScriptPackage.Literals.VOID_TYPE_REF;
  }

} //VoidTypeRefImpl
