/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.ClassRef#getReferencedClass <em>Referenced Class</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getClassRef()
 * @model
 * @generated
 */
public interface ClassRef extends SingleTypeRef
{
  /**
   * Returns the value of the '<em><b>Referenced Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Referenced Class</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Referenced Class</em>' reference.
   * @see #setReferencedClass(duc.uscript.uScript.Class)
   * @see duc.uscript.uScript.UScriptPackage#getClassRef_ReferencedClass()
   * @model
   * @generated
   */
  duc.uscript.uScript.Class getReferencedClass();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.ClassRef#getReferencedClass <em>Referenced Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Referenced Class</em>' reference.
   * @see #getReferencedClass()
   * @generated
   */
  void setReferencedClass(duc.uscript.uScript.Class value);

} // ClassRef
