/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Draw Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.DrawExpr#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getDrawExpr()
 * @model
 * @generated
 */
public interface DrawExpr extends Expression
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see duc.uscript.uScript.UScriptPackage#getDrawExpr_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.DrawExpr#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // DrawExpr
