/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gaussian Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getGaussianRef()
 * @model
 * @generated
 */
public interface GaussianRef extends UTypeRef
{
} // GaussianRef
