/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integer Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getIntegerTypeRef()
 * @model
 * @generated
 */
public interface IntegerTypeRef extends SingleTypeRef
{
} // IntegerTypeRef
