/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Method Call2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.MethodCall2#getMethod <em>Method</em>}</li>
 *   <li>{@link duc.uscript.uScript.MethodCall2#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getMethodCall2()
 * @model
 * @generated
 */
public interface MethodCall2 extends Expression
{
  /**
   * Returns the value of the '<em><b>Method</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Method</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method</em>' reference.
   * @see #setMethod(Method)
   * @see duc.uscript.uScript.UScriptPackage#getMethodCall2_Method()
   * @model
   * @generated
   */
  Method getMethod();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.MethodCall2#getMethod <em>Method</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Method</em>' reference.
   * @see #getMethod()
   * @generated
   */
  void setMethod(Method value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link duc.uscript.uScript.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see duc.uscript.uScript.UScriptPackage#getMethodCall2_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // MethodCall2
