/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.NewObject#getType <em>Type</em>}</li>
 *   <li>{@link duc.uscript.uScript.NewObject#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getNewObject()
 * @model
 * @generated
 */
public interface NewObject extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(duc.uscript.uScript.Class)
   * @see duc.uscript.uScript.UScriptPackage#getNewObject_Type()
   * @model
   * @generated
   */
  duc.uscript.uScript.Class getType();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.NewObject#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(duc.uscript.uScript.Class value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link duc.uscript.uScript.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see duc.uscript.uScript.UScriptPackage#getNewObject_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // NewObject
