/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>New UObject</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.NewUObject#getType <em>Type</em>}</li>
 *   <li>{@link duc.uscript.uScript.NewUObject#getArgs <em>Args</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getNewUObject()
 * @model
 * @generated
 */
public interface NewUObject extends Expression
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(UTypeRef)
   * @see duc.uscript.uScript.UScriptPackage#getNewUObject_Type()
   * @model containment="true"
   * @generated
   */
  UTypeRef getType();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.NewUObject#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(UTypeRef value);

  /**
   * Returns the value of the '<em><b>Args</b></em>' containment reference list.
   * The list contents are of type {@link duc.uscript.uScript.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Args</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Args</em>' containment reference list.
   * @see duc.uscript.uScript.UScriptPackage#getNewUObject_Args()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getArgs();

} // NewUObject
