/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Null</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getNull()
 * @model
 * @generated
 */
public interface Null extends Expression
{
} // Null
