/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends Symbol
{
} // Parameter
