/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rayleigh Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getRayleighRef()
 * @model
 * @generated
 */
public interface RayleighRef extends UTypeRef
{
} // RayleighRef
