/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getSingleTypeRef()
 * @model
 * @generated
 */
public interface SingleTypeRef extends TypeRef
{
} // SingleTypeRef
