/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
