/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>UType Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link duc.uscript.uScript.UTypeRef#getGenericType <em>Generic Type</em>}</li>
 * </ul>
 *
 * @see duc.uscript.uScript.UScriptPackage#getUTypeRef()
 * @model
 * @generated
 */
public interface UTypeRef extends TypeRef
{
  /**
   * Returns the value of the '<em><b>Generic Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Generic Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Generic Type</em>' containment reference.
   * @see #setGenericType(SingleTypeRef)
   * @see duc.uscript.uScript.UScriptPackage#getUTypeRef_GenericType()
   * @model containment="true"
   * @generated
   */
  SingleTypeRef getGenericType();

  /**
   * Sets the value of the '{@link duc.uscript.uScript.UTypeRef#getGenericType <em>Generic Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Generic Type</em>' containment reference.
   * @see #getGenericType()
   * @generated
   */
  void setGenericType(SingleTypeRef value);

} // UTypeRef
