/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getVariableDeclaration()
 * @model
 * @generated
 */
public interface VariableDeclaration extends Assignee, Symbol
{
} // VariableDeclaration
