/**
 * generated by Xtext 2.16.0
 */
package duc.uscript.uScript;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Void Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see duc.uscript.uScript.UScriptPackage#getVoidTypeRef()
 * @model
 * @generated
 */
public interface VoidTypeRef extends SingleTypeRef
{
} // VoidTypeRef
